const word = {
  phenomenon:
    '现象 /fəˈnɒmɪnən/；现象；杰出的人，非凡的人（或事物）；（哲学）现象',
  inspire:
    '激励，鼓舞；赋予灵感，激发（想法）；使产生（感觉或情感）；引起，导致；吸气，吸入',
  abroad: '国外，海外',
  staff: '职员，职员的',
  staffed: '雇佣的工作人员',
  volunteer: '自愿者',
  legacy: '遗产；遗赠财物；遗留问题；后遗症 /ˈleɡəsi/',
  'planning documents': '规划书',
  pledge: '/pledʒ/誓言，保证，承诺',
  'lever a nation of sport lovers away from their couches':
    '把全国的体育爱好者从沙发上拉起来 ',
  couche: '躺',
  fitter:
    'n. 装配工；试衣裁缝，地毯安装工；（服装或鞋子的）质检员; adj. 更健壮的；更适合的；更能胜任的；更正确的',
  'but the general population was growing faster': '但是总体人口增长更快',
  'Worse, the numbers are now falling at an accelerating rate':
    '更糟的是，数字现在正在以更快的速度下降',
  accelerate: ' 加速；促进；增加',
  rate: ' 比率，率；速度',
  pave: '用石板（或砖）铺（路）；为……铺平道路，创造条件（pave the way for sth./sb.',
  provision: 'n:规定，条款，供应品，v:供给...实物/必需品',
  preside: '主持',
  squeeze: '挤；紧握；勒索；压榨',
  authority: '当局，权威，权利',
  decline: '下降，衰退',
  strategy: '策略，对策，行动计划；战略，战略学',
  thrive: '茁壮成长，兴旺，繁荣',
  boost: '是增长，推动',
  mass: '块，团，群众，民众，大量',
  emphasize: '强调，着重',
  elitism: '精英主义',
  attract: '吸引',
  supervise:' 监督；管理；指导；主管；照看',
  facility: '设施，工具，设备',
  tolerant: '宽容的,容忍的；（植物、动物、机器）能耐……的，有耐受性的',
  critical: '批判的，批评的',
  sympathetic: '同情的，有同情心的；赞同的，支持的',
  uncertain: '犹豫的，无把握的，不确定的',
  suck: '',
}

const wordTrans = {
  suck: '将……卷入，吞没；使卷入， 吸',
  maximal: '最大的，最高的，最大限度的',
  engagement: '参与度；约会，婚约，诺言',
  disengage: '使脱离；解开；解除',
  routine: 'n: 日常，乏味，平常；adj:常规的，例行的；平常的；乏味的',
  tablet: '碑；药片；写字板；小块；平板电脑',
  verbal: '口头的，非书面的；用言辞的',
  nonverbal: '不用语言的；不用动词的',
  interaction: 'n:相互作用，相互影响；交流',
  interact: 'v:相互交流，互动；相互作用，相互影响',
  separate: '分开的；单独的；不同的；各自的；不受影响的',
  tension: '紧张，焦虑；紧张关系，紧张局势；矛盾，冲突；',
  excite: ' 使兴奋，使激动',
  excited: ' 激动的，兴奋的；忧虑的，气愤的；已激发的，受激的；性兴奋的',
  attention: '注意；注意力',
  infant: '婴儿，幼儿',
  wire: ' 电线；金属丝；电报',
  absorb: '吸收；使并入，纳入；同化，汲取',
  'absorb in': '集中精力做某事；全神贯注于',
  extremely: '极度，非常',
  disconcert: '使困惑，使不安，不仓皇失措',
  disconcerting: '令人不安的，打扰人的',
  cite: '引用，援引；引证，引以为例',
  devise: '设计，发明，想出',
  visual: '视觉的',
  feedback: '反馈',
  distress: '忧虑，悲伤；贫困；',
  capture: '俘获；夺得；捕捉',
  exquisitely: '精致地，精巧地，敏锐地',
  sensitive: '敏感的',
  insensitive: '不敏感的',
  emotional: '情感的',
  oppressive: '压迫的，暴虐的，不公的 ',
  ideology: '意识形态',
  fantasize: '幻想，想像',
  expose: '揭露，揭发；使曝光；显示',
  neglect: '忽视',
  shower: '沐浴',
  interpersonal: '人际交往',
  appetite: '食欲',
  distract: '使分心',
  mention: '提到，谈到',
  constant: '持续不断的',
  exposure: '暴露，接触， 曝光',
  wild: '野生的；野蛮的；狂热的；荒凉的',
  attentive: '注意力',

}